In [12]:
# 1. CONFIGURACIÓN DEL MOTOR Y CONEXIONES (ORACLE SQL)
import re
import os
import time
import threading
import pandas as pd
from sqlalchemy import create_engine, inspect, text, bindparam

MOTOR = "oracle"

CONEXIONES = {
    "oracle": {
        "destino": "oracle+oracledb://system:Dulcee16$@localhost:1521/?service_name=XE",
    }
}

engine_destino = create_engine(CONEXIONES[MOTOR]["destino"])
print("Configuración de motor Oracle cargada exitosamente.")

Configuración de motor Oracle cargada exitosamente.

In [13]:
import pandas as pd
import time

print("Conectando con la base de datos Oracle...")
inicio = time.time()

# Consulta SQL para traer todos los registros de la tabla RAW
query_extraccion = "SELECT * FROM DATAMART_RAW"

# Leemos directamente desde la base de datos usando el motor (engine_destino) que ya creaste arriba
data_raw = pd.read_sql(query_extraccion, con=engine_destino)

fin = time.time()
print(f"¡Datos extraídos con éxito desde Oracle! Total de registros: {len(data_raw)}")
print(f"Tiempo de extracción: {fin - inicio:.2f} segundos.")

Conectando con la base de datos Oracle...
¡Datos extraídos con éxito desde Oracle! Total de registros: 541709
Tiempo de extracción: 2.93 segundos.

In [14]:
#visualizacion
# Visualizar las primeras 5 filas del conjunto de datos para verificar las columnas
data_raw.head()

,invoiceno,stockcode,description,quantity,invoicedate,unitprice,customerid,country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,01-12-2010 8:26,"2,55",17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,01-12-2010 8:26,"3,39",17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,01-12-2010 8:26,"2,75",17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,01-12-2010 8:26,"3,39",17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,01-12-2010 8:26,"3,39",17850.0,United Kingdom

In [15]:
# Revisar el total de registros, nombres exactos de columnas y tipos de datos
data_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541709 entries, 0 to 541708
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   invoiceno    541709 non-null  object
 1   stockcode    541709 non-null  object
 2   description  540255 non-null  object
 3   quantity     541709 non-null  object
 4   invoicedate  541709 non-null  object
 5   unitprice    541709 non-null  object
 6   customerid   406636 non-null  object
 7   country      541709 non-null  object
dtypes: object(8)
memory usage: 33.1+ MB

In [16]:
# Creamos la copia exacta en una nueva variable para empezar a trabajar de forma segura
df_ejercicio = data_raw.copy()

# Inicializamos una columna de control de trazabilidad de estados (Ev2)
df_ejercicio['ESTADO'] = 'Sin Cambios'

# Confirmamos que la copia se generó correctamente mostrando su cabecera
df_ejercicio.head()

,invoiceno,stockcode,description,quantity,invoicedate,unitprice,customerid,country,ESTADO
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,01-12-2010 8:26,"2,55",17850.0,United Kingdom,Sin Cambios
1,536365,71053,WHITE METAL LANTERN,6,01-12-2010 8:26,"3,39",17850.0,United Kingdom,Sin Cambios
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,01-12-2010 8:26,"2,75",17850.0,United Kingdom,Sin Cambios
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,01-12-2010 8:26,"3,39",17850.0,United Kingdom,Sin Cambios
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,01-12-2010 8:26,"3,39",17850.0,United Kingdom,Sin Cambios

In [19]:
# =============================================================================
# SECCIÓN 4: TRANSFORMACIÓN, LIMPIEZA, FILTROS Y TRADUCCIÓN COMPLETA
# =============================================================================
from datetime import datetime
# --- 1. TRADUCCIÓN DE COLUMNAS (ENCABEZADOS) ---
columnas_espanol = {
    'InvoiceNo': 'Nro_Boleta',
    'StockCode': 'Codigo_Producto',
    'Description': 'Descripcion',
    'Quantity': 'Cantidad',
    'InvoiceDate': 'Fecha_Venta',
    'UnitPrice': 'Precio_Unitario',
    'CustomerID': 'CustomerID', 
    'Country': 'Pais'
}
df_ejercicio = df_ejercicio.rename(columns=columnas_espanol)


# --- 2. REGLA DE DESCARTE POR NULOS CRÍTICOS ---
mask_nulos = df_ejercicio['CUSTOMERID'].isna() | df_ejercicio['Nro_Boleta'].isna()
df_ejercicio.loc[mask_nulos, 'ESTADO'] = 'Descartado'


# --- 3. DICCIONARIOS DE TRADUCCIÓN PARA LOS DATOS ---

# Diccionario para Países
diccionario_paises = {
    'United Kingdom': 'Reino Unido',
    'France': 'Francia',
    'Germany': 'Alemania',
    'Spain': 'España',
    'EIRE': 'Irlanda',
    'Portugal': 'Portugal',
    'Norway': 'Noruega',
    'Australia': 'Australia'
}

# Diccionario para las Descripciones de Productos (Mapeo de los más comunes)
# Puedes ir agregando aquí más productos según vayas viendo en tu archivo
diccionario_productos = {
    'WHITE HANGING HEART T-LIGHT HOLDER': 'PORTAVELAS CORAZÓN COLGANTE BLANCO',
    'SET 7 BABUSHKA NESTING BOXES': 'SET DE 7 CAJAS NIDIFICADAS BABUSHKA',
    'ASSORTED COLOUR BIRD ORNAMENT': 'ADORNO DE PÁJARO EN COLORES SURTIDOS',
    'CREAM CUPID HEARTS COAT HANGER': 'PERCHERO CORAZONES DE CUPIDO CREMA',
    'KNITTED UNION FLAG HOT WATER BOTTLE': 'BOLSA DE AGUA CALIENTE BANDERA TEJIDA',
    'RED WOOLLY TOWEL TERMINATION': 'TERMINACIÓN DE TOALLA DE LANA ROJA',
    'HAND WARMER RED POLKA DOT': 'CALENTADOR DE MANOS CON LUNARES ROJOS',
    'RED WOOLLY HOTTIE WHITE HEART': 'CALENTADOR DE LANA ROJO CORAZÓN BLANCO'
}
# --- 3. DICCIONARIO DE PALABRAS CLAVE PARA TRADUCCIÓN AUTOMÁTICA ---
# Este diccionario traduce los componentes individuales de cualquier producto automáticamente
diccionario_palabras = {
    # Colores
    'WHITE': 'BLANCO', 'RED': 'ROJO', 'BLUE': 'AZUL', 'GREEN': 'VERDE', 'PINK': 'ROSADO',
    'BLACK': 'NEGRO', 'YELLOW': 'AMARILLO', 'GOLD': 'DORADO', 'SILVER': 'PLATEADO', 'GREY': 'GRIS',
    # Materiales y Atributos
    'METAL': 'METAL', 'GLASS': 'VIDRIO', 'WOOD': 'MADERA', 'WOODEN': 'DE MADERA', 'WOOLLY': 'DE LANA',
    'KNITTED': 'TEJIDO', 'CERAMIC': 'CERÁMICA', 'VINTAGE': 'ESTILO RETRO', 'RETRO': 'RETRO',
    # Tipos de Objetos comunes en el eCommerce
    'LANTERN': 'FAROL/LINTERNA', 'HEART': 'CORAZÓN', 'HEARTS': 'CORAZONES', 'HOTTIE': 'CALENTADOR',
    'HANGING': 'COLGANTE', 'LIGHT': 'LUZ', 'HOLDER': 'SOPORTE', 'SET': 'SET', 'BOXES': 'CAJAS',
    'NESTING': 'NIDIFICADAS', 'ASSORTED': 'SURTIDO', 'ASST': 'SURTIDO', 'COLOUR': 'COLOR',
    'BIRD': 'PÁJARO', 'ORNAMENT': 'ADORNO', 'BAG': 'BOLSA', 'STAR': 'ESTRELLA', 'STARS': 'ESTRELLAS',
    'CUP': 'TAZA', 'MUG': 'TAZÓN', 'MUGS': 'TAZONES', 'BOTTLE': 'BOTELLA', 'SIGN': 'LETRERO',
    'CLOCK': 'RELOJ', 'CANDLE': 'VELA', 'CANDLES': 'VELAS', 'FRAME': 'MARCO', 'BOX': 'CAJA',
    'DESIGN': 'DISEÑO', 'PACK': 'PACK', 'PK': 'PACK', 'CHRISTMAS': 'NAVIDAD', 'CAKE': 'PASTEL/QUEQUE',
    'TEA': 'TÉ', 'COFFEE': 'CAFÉ', 'KITCHEN': 'COCINA', 'GARDEN': 'JARDÍN', 'HOME': 'HOGAR',
    # Más palabras clave del set
    'HOOK': 'GANCHO', 'HOOKS': 'GANCHOS', 'WARMER': 'CALENTADOR', 'HAND': 'MANO', 
    'POLKA': 'LUNARES', 'DOT': 'PUNTO', 'COAT': 'ABRIGO/ROPA', 'HANGER': 'PERCHERO',
    'FLAG': 'BANDERA', 'HOT': 'CALIENTE', 'WATER': 'AGUA', 'TOWEL': 'TOALLA'
}

# --- 4. APLICACIÓN DE TRADUCCIÓN INTELIGENTE Y NORMALIZACIÓN ---
def limpiar_y_traducir_descripcion(row):
    if row['ESTADO'] == 'Descartado' or pd.isna(row['Descripcion']):
        return row['Descripcion']
    
    # 1. Limpiamos y pasamos a mayúsculas
    texto_original = str(row['Descripcion']).strip().upper()
    if texto_original in diccionario_productos:
        return diccionario_productos[texto_original]
    
    # 2. Separamos la descripción en palabras individuales
    palabras = texto_original.split()
    palabras_traducidas = [diccionario_palabras.get(p, p) for p in palabras]
    return " ".join(palabras_traducidas)
    
    # 3. Traducimos cada palabra si existe en nuestro diccionario, si no, dejamos la original
    palabras_traducidas = [diccionario_palabras.get(palabra, palabra) for palabra in palabras]
    
    # 4. Volvemos a unir las palabras en una sola frase en español
    return " ".join(palabras_traducidas)

# Aplicamos la función inteligente a toda la columna
df_ejercicio['Descripcion'] = df_ejercicio.apply(limpiar_y_traducir_descripcion, axis=1)

# --- 4. APLICACIÓN DE TRADUCCIONES Y NORMALIZACIÓN DE DESCRIPCIONES ---
# Pasamos primero a mayúsculas limpias
def limpiar_y_traducir_descripcion(row):
    if row['ESTADO'] == 'Descartado' or pd.isna(row['Descripcion']):
        return row['Descripcion']
    
    texto_limpio = str(row['Descripcion']).strip().upper()
    
    # Si el producto está en nuestro diccionario, lo traduce; si no, deja el original limpio
    return diccionario_productos.get(texto_limpio, texto_limpio)

df_ejercicio['Descripcion'] = df_ejercicio.apply(limpiar_y_traducir_descripcion, axis=1)


# --- 5. APLICACIÓN DE TRADUCCIÓN DE PAÍSES E IMPUTACIÓN ---
df_ejercicio['Pais'] = df_ejercicio['Pais'].replace(diccionario_paises)

# Imputación de nulos secundarios
campos_opcionales = ['Pais', 'Descripcion']
for campo in campos_opcionales:
    mask_imputar = df_ejercicio[campo].isna() & (df_ejercicio['ESTADO'] != 'Descartado')
    df_ejercicio.loc[mask_imputar, 'ESTADO'] = 'Transformados'
    df_ejercicio[campo] = df_ejercicio[campo].fillna('NO DISPONIBLE')

    
# --- 6. ESTANDARIZACIÓN DE FECHAS AL ESTÁNDAR ISO 8601 (SIN INVENTAR DATOS) ---
# Agregamos formatos comunes incluyendo variantes con guiones y barras
formatos_conocidos = [
    "%d/%m/%Y %H:%M", "%m/%d/%Y %H:%M", 
    "%Y-%m-%d %H:%M:%S", "%Y-%m-%d",
    "%d-%m-%Y %H:%M", "%m-%d-%Y %H:%M"
]

def estandarizar_fecha_comercial(fecha_str):
    # Si viene vacío o es nulo nativo, se queda SIN REGISTRO (None)
    if pd.isna(fecha_str) or str(fecha_str).strip() == "":
        return None
        
    for fmt in formatos_conocidos:
        try:
            # Convierte la fecha real según su formato original y la exporta como YYYY-MM-DD
            return datetime.strptime(str(fecha_str).strip(), fmt).strftime("%Y-%m-%d")
        except ValueError:
            continue
            
    # Si tiene un texto no reconocible, se queda SIN REGISTRO (None) en lugar de inventar el 1900
    return None

# Guardamos una copia para comparar estados antes de aplicar el cambio
fechas_originales = df_ejercicio['Fecha_Venta'].copy()

# Aplicamos la estandarización pura
df_ejercicio['Fecha_Venta'] = df_ejercicio['Fecha_Venta'].apply(estandarizar_fecha_comercial)

# Marcamos como transformados solo los que cambiaron de formato pero siguen teniendo una fecha válida
mask_fecha_mutada = (df_ejercicio['Fecha_Venta'] != fechas_originales) & (df_ejercicio['Fecha_Venta'].notna()) & (df_ejercicio['ESTADO'] != 'Descartado')
df_ejercicio.loc[mask_fecha_mutada, 'ESTADO'] = 'Transformados'

print("¡Estandarización temporal ajustada según tus requerimientos!")

fechas_originales = df_ejercicio['Fecha_Venta'].copy()
df_ejercicio['Fecha_Venta'] = df_ejercicio['Fecha_Venta'].apply(estandarizar_fecha_comercial)

mask_fecha_mutada = (df_ejercicio['Fecha_Venta'] != fechas_originales) & (df_ejercicio['ESTADO'] != 'Descartado')
df_ejercicio.loc[mask_fecha_mutada, 'ESTADO'] = 'Transformados'

print("¡Transformación, filtros y traducción masiva completados!")

KeyError: 'CUSTOMERID'

In [16]:
import hashlib
def cifrar_identificador_cliente(id_cliente):
    if pd.isna(id_cliente) or id_cliente == 'NO DISPONIBLE':
        return 'CLIENTE_ANONIMO'
    hash_objeto = hashlib.sha256(str(id_cliente).encode('utf-8'))
    return hash_objeto.hexdigest()[:12].upper()

mask_validos = df_ejercicio['ESTADO'] != 'Descartado'
df_ejercicio['CustomerID_CIFRADO'] = df_ejercicio['CustomerID']
df_ejercicio.loc[mask_validos, 'CustomerID_CIFRADO'] = df_ejercicio.loc[mask_validos, 'CustomerID'].apply(cifrar_identificador_cliente)

# Visualizar el DataFrame con los clientes ya protegidos criptográficamente
df_ejercicio.head(20)

C:\Users\isido\AppData\Local\Temp\ipykernel_3564\910072608.py:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['54CDE5DBB60A' '54CDE5DBB60A' '54CDE5DBB60A' ... '4D727C2AA8B2'
 '4D727C2AA8B2' '4D727C2AA8B2']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df_ejercicio.loc[mask_validos, 'CustomerID_CIFRADO'] = df_ejercicio.loc[mask_validos, 'CustomerID'].apply(cifrar_identificador_cliente)

,Nro_Boleta,Codigo_Producto,Descripcion,Cantidad,Fecha_Venta,Precio_Unitario,CustomerID,Pais,ESTADO,CustomerID_CIFRADO
0,536365,85123A,PORTAVELAS CORAZÓN COLGANTE BLANCO,6,2010-12-01,"2,55",17850.0,Reino Unido,Transformados,54CDE5DBB60A
1,536365,71053,BLANCO METAL FAROL/LINTERNA,6,2010-12-01,"3,39",17850.0,Reino Unido,Transformados,54CDE5DBB60A
2,536365,84406B,PERCHERO CORAZONES DE CUPIDO CREMA,8,2010-12-01,"2,75",17850.0,Reino Unido,Transformados,54CDE5DBB60A
3,536365,84029G,BOLSA DE AGUA CALIENTE BANDERA TEJIDA,6,2010-12-01,"3,39",17850.0,Reino Unido,Transformados,54CDE5DBB60A
4,536365,84029E,ROJO DE LANA CALENTADOR BLANCO HEART.,6,2010-12-01,"3,39",17850.0,Reino Unido,Transformados,54CDE5DBB60A
5,536365,22752,SET DE 7 CAJAS NIDIFICADAS BABUSHKA,2,2010-12-01,"7,65",17850.0,Reino Unido,Transformados,54CDE5DBB60A
6,536365,21730,VIDRIO ESTRELLA FROSTED T-LIGHT SOPORTE,6,2010-12-01,"4,25",17850.0,Reino Unido,Transformados,54CDE5DBB60A
7,536366,22633,MANO CALENTADOR UNION JACK,6,2010-12-01,"1,85",17850.0,Reino Unido,Transformados,54CDE5DBB60A
8,536366,22632,CALENTADOR DE MANOS CON LUNARES ROJOS,6,2010-12-01,"1,85",17850.0,Reino Unido,Transformados,54CDE5DBB60A
9,536367,84879,ADORNO DE PÁJARO EN COLORES SURTIDOS,32,2010-12-01,"1,69",13047.0,Reino Unido,Transformados,86314FA84983
10,536367,22745,POPPY'S PLAYHOUSE BEDROOM,6,2010-12-01,"2,1",13047.0,Reino Unido,Transformados,86314FA84983
11,536367,22748,POPPY'S PLAYHOUSE COCINA,6,2010-12-01,"2,1",13047.0,Reino Unido,Transformados,86314FA84983
12,536367,22749,FELTCRAFT PRINCESS CHARLOTTE DOLL,8,2010-12-01,"3,75",13047.0,Reino Unido,Transformados,86314FA84983
13,536367,22310,IVORY TEJIDO TAZÓN COSY,6,2010-12-01,"1,65",13047.0,Reino Unido,Transformados,86314FA84983
14,536367,84969,CAJA OF 6 SURTIDO COLOR TEASPOONS,6,2010-12-01,"4,25",13047.0,Reino Unido,Transformados,86314FA84983
15,536367,22623,CAJA OF ESTILO RETRO JIGSAW BLOCKS,3,2010-12-01,"4,95",13047.0,Reino Unido,Transformados,86314FA84983
16,536367,22622,CAJA OF ESTILO RETRO ALPHABET BLOCKS,2,2010-12-01,"9,95",13047.0,Reino Unido,Transformados,86314FA84983
17,536367,21754,HOGAR BUILDING BLOCK WORD,3,2010-12-01,"5,95",13047.0,Reino Unido,Transformados,86314FA84983
18,536367,21755,LOVE BUILDING BLOCK WORD,3,2010-12-01,"5,95",13047.0,Reino Unido,Transformados,86314FA84983
19,536367,21777,RECIPE CAJA WITH METAL CORAZÓN,4,2010-12-01,"7,95",13047.0,Reino Unido,Transformados,86314FA84983

In [17]:
# Despliegue de métricas en pantalla
total_lote = len(df_ejercicio)
trans = len(df_ejercicio[df_ejercicio['ESTADO'] == 'Transformados'])
descartados = len(df_ejercicio[df_ejercicio['ESTADO'] == 'Descartado'])
sin_cambios = len(df_ejercicio[df_ejercicio['ESTADO'] == 'Sin Cambios'])

print(f"Total registros evaluados en DataMart: {total_lote}")
print(f"Registros Transformados con éxito:    {trans}")
print(f"Registros Descartados por anomalías:  {descartados}")

# Guardar logs de auditoría física (Registros corruptos descartados)
df_errores = df_ejercicio[df_ejercicio['ESTADO'] == 'Descartado']
if not df_errores.empty:
    df_errores.to_csv("log_registros_descartados_datamart.csv", index=False, encoding="utf-8-sig")

# Guardar archivo maestro definitivo listo para la Base de Datos Relacional / Dashboard
df_final_exito = df_ejercicio[df_ejercicio['ESTADO'] != 'Descartado']
df_final_exito.to_csv("datamart_listo_para_cargar.csv", index=False, encoding="utf-8-sig")

print("\nPipeline finalizado. Archivos generados correctamente en tu directorio.")

Total registros evaluados en DataMart: 541909
Registros Transformados con éxito:    406829
Registros Descartados por anomalías:  135080

Pipeline finalizado. Archivos generados correctamente en tu directorio.